name: Publish 
on:
  workflow_dispatch:
  push:
    branches:
      - main
env: 
  AZURE_WEBAPP_NAME: csharp-dotnet7-test
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - name: Restore
        run: dotnet restore ./Integrify-s-Project/Integrify-s-Project.sln
      - name: Build
        run: dotnet build ./Integrify-s-Project/Integrify-s-Project.sln --configuration Release --no-restore
      - name: Publish
        run: dotnet publish ./Integrify-s-Project/Integrify-s-Project.sln --configuration Release --no-build --output '${{env.AZURE_WEBAPP_PACKAGE_PATH}}'
      - name: Deployment
        uses: actions/webapps-deploy@v2
        with: 
          app-name: "${{env.AZURE_WEBAPP_NAME}}"
          publish-profile: ${{secrets.AZURE_PUBLISH_PROFILE}}
          package: "${{env.AZURE_WEBAPP_PACKAGE_PATH}}"
      
